- name: templates
  params: 'CREATE TABLE templates
         (
           template_id SERIAL PRIMARY KEY,
           template_name VARCHAR(255) NOT NULL,
           template_data TEXT NOT NULL
         )'
- name: config
  params: 'CREATE TABLE configuration
         (
            config_id INT PRIMARY KEY,
            config_name VARCHAR(40) NOT NULL,
            environments_skip TEXT,
            services_skip TEXT,
            sending_timeout INT NOT NULL
         )'
- name: topics
  params: 'CREATE TABLE topics
         (
           topic_id SERIAL PRIMARY KEY,
           topic_name VARCHAR(40) NOT NULL,
           templ_id SERIAL REFERENCES templates
         )'
