- name: db_config
  params:
    host: '80.158.41.159'
    port: 5432
    user: 'postgres'
- name: templates
  params: 'CREATE TABLE templates
         (
           template_id SERIAL PRIMARY KEY,
           template_name VARCHAR(255) NOT NULL,
           template_data TEXT NOT NULL
         )'
- name: config
  params: 'CREATE TABLE configuration
         (
            config_id SERIAL PRIMARY KEY,
            config_name VARCHAR(40) NOT NULL,
            alerta_endpoint VARCHAR(255),
            alerta_timeout INT NOT NULL,
            alerta_debug BOOLEAN NOT NULL
         )'
- name: topics
  params: 'CREATE TABLE topics
         (
           topic_id SERIAL PRIMARY KEY,
           topic_name VARCHAR(40) NOT NULL,
           zulip_to VARCHAR(255),
           zulip_subject VARCHAR(255),
           templ_id SERIAL REFERENCES templates
         )'
